### ISSUE TITLE
cannot build - problem with windows 10 event.h

### ISSUE THREAD

**Issue by CGAndersonSea** [walbourn/directxtk12modelviewer#1]
![image](https://user-images.githubusercontent.com/41025371/44360754-b123b580-a470-11e8-9a6c-dfe8c54c97b2.png)
 am using 10.0.17134.0  sdk (installed via visual studio installer, in fact) as instructed with visual studio 2017 and using the correct sln with the correct startup project. 
and get the error:
C7510: 'Callback': use of dependent template name must be prefixed with 'template'. the error is reporting against Microsoft's own header, winrt/wrl/event.h (316 and 324)

Since this requires one modify a Microsoft file to fix it, seems like it would be better to fix either the sample or the sdk by microsoft?

**Comment by walbourn** [comment]
The VS 2017 updates are improving the conformance of [two-phase name lookup](https://blogs.msdn.microsoft.com/vcblog/2017/09/11/two-phase-name-lookup-support-comes-to-msvc/) which is enabled by ``/permissive-`` (a.k.a [Conformance Mode](https://blogs.msdn.microsoft.com/vcblog/2016/11/16/permissive-switch/)). The Windows 10 SDK aren't quite keeping up...

There is a fix to WRL to resolve this issue which will ship in a future Windows 10 SDK release. You can workaround the issue by either adding ``/Zc:twoPhase-`` to the Additional Options, or turning off Conformance Mode.

Note that I've done a new release of the toolkit and samples to support VS 2017 (15.8), so you should update to those and see if that fixes the problem for you.

**Comment by CGAndersonSea** [comment]
thanks for the quick turnaround and the explanation.  I tried the zip file but got the same errors. perhaps it takes a while for the zip to update. So, I tried turning off conformance mode and it compiled. however, while it runs, it doesn't load an sdkmesh. I tried several, including the ball.sdkmesh you uploaded on your site. All of them exception out in ResourceUploadBatch.cpp line 402 (the fence).  No clue as to why, sorry. (unless it needs conformance mode, but that seems unlikely).

Unhandled exception at 0x00007FF8E2ADA388 (KernelBase.dll) in DirectXTKModelViewer_Desktop_2017_Win10.exe: 0x0000087A (parameters: 0x0000000000000001, 0x0000007641AF91F0, 0x0000007641AFB0F0). occurred

**Comment by walbourn** [comment]
Did you get any debug output in the debug window? Maybe you are missing the texture files?

**Comment by CGAndersonSea** [comment]
Yep, that was it. I grabbed ball.sdkmesh but  didn't realize it would crash if it didn't have it's ball.dds file. 
Thanks!
p.s. someone ought to update the 'get the directx 12 including raytracing' notes/blog/posting that 10.0.17134.12 is the sdk you need and yes, it's the same one you get when installing/updating VS2017. I just uninstalled it b/c Visual Studio 2017 installed it, and installed the win 10 sdk from the windows sdk website...because it seemed to be implying that I had the wrong one. left hand, right hand, i suppose!

Unless of course, something is missing from the VS2017 version of it?
Anyway, thanks!
